package brightspot.itemstream.podcast;

import brightspot.util.TypeStateValueAdapter;

public class DynamicPodcastEpisodeItemStreamAllMatchAdapter extends TypeStateValueAdapter<DynamicPodcastEpisodeItemStreamAllMatch, brightspot.module.list.podcast.DynamicPodcastEpisodeItemStreamAllMatch> {
}
